model:
  backbone: Etinynet # available backbone architectures: Etinynet, Squeezenet
  num_classes: 1

training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 0.0001
  weight_decay: 0.0001
  momentum: 0.9

data:
  train_dir: "./data/train"
  val_dir: "./data/val"
  image_size: (224, 224)
  num_classes: 1

augmentation:
  random_crop: True
  random_rotation: True
  random_flip: True

checkpointing:
  checkpoint_dir: "./checkpoints"
  save_every: 10

evaluation:
  metrics: ["mAP"]
  evaluate_every: 5

hyperparameter_tuning:
  search_space:
    learning_rate: [0.0001, 0.001, 0.01]
    weight_decay: [0.0001, 0.001, 0.01]
  values_to_try:
    learning_rate: [0.0001, 0.001]
    weight_decay: [0.0001, 0.001]